### ISSUE TITLE
League creation issue (running local with sql.lite) 

### ISSUE THREAD

**Issue by seawolff** [bwentzloff/afs#91]
Just setup a version of this locally with your README directions. 
Created a league just fine and set the name and points etc and created it.

However, once I'm taken to the league view I don't see my league name and my invite code link is missing.
<img width="760" alt="Screenshot 2020-02-22 01 11 37" src="https://user-images.githubusercontent.com/147572/75088260-5315d980-5510-11ea-8b0d-7dd58d68c282.png">

Can you help me find what the issue is? Would love to help out.

Thanks!

**Comment by bwentzloff** [comment]
Looks like everything on the screen is showing the defaults which leads me to believe maybe you’re not successfully connecting to the database maybe? Does the browser console show any errors?

**Comment by seawolff** [comment]
@bwentzloff ah yes

```
Error: Request failed with status code 500
    at createError (app.js:1812)
    at settle (app.js:1975)
    at XMLHttpRequest.handleLoad (app.js:1345)
```

**Comment by seawolff** [comment]
Pretty sure you can recreate by just making a new sql.lite db and trying to create a league.

**Comment by bwentzloff** [comment]
Ok, since you’re getting a 500, check in storage/logs and you should have a more specific error in there pointing you to what’s happening.

**Comment by seawolff** [comment]
@bwentzloff when I load the page:

```
[2020-02-22 16:50:18] local.ERROR: Trying to get property 'current_week' of non-object {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to get property 'current_week' of non-object at /Users/chris/Documents/afs/app/Http/Controllers/LeagueController.php:1027)
[stacktrace]
#0 /Users/chris/Documents/afs/app/Http/Controllers/LeagueController.php(1027): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/Users/chris/Do...', 1027, Array)
#1 [internal function]: App\\Http\\Controllers\\LeagueController->getLeagueInfo('3')
#2 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#3 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('getLeagueInfo', Array)
#4 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\LeagueController), 'getLeagueInfo')
#5 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#6 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#7 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#13 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#14 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#15 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#16 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#17 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/chris/Documents/afs/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#36 /Users/chris/Documents/afs/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#37 /Users/chris/Documents/afs/server.php(21): require_once('/Users/chris/Do...')
#38 {main}
"}
[2020-02-22 16:50:18] local.ERROR: Trying to get property 'current_week' of non-object {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to get property 'current_week' of non-object at /Users/chris/Documents/afs/app/Http/Controllers/LeagueController.php:1027)
[stacktrace]
#0 /Users/chris/Documents/afs/app/Http/Controllers/LeagueController.php(1027): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/Users/chris/Do...', 1027, Array)
#1 [internal function]: App\\Http\\Controllers\\LeagueController->getLeagueInfo('3')
#2 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#3 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('getLeagueInfo', Array)
#4 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\LeagueController), 'getLeagueInfo')
#5 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#6 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#7 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#13 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#14 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#15 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#16 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#17 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/chris/Documents/afs/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /Users/chris/Documents/afs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#36 /Users/chris/Documents/afs/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#37 /Users/chris/Documents/afs/server.php(21): require_once('/Users/chris/Do...')
#38 {main}
"}

```

**Comment by bwentzloff** [comment]
That means it couldn’t find the league in the database. Can you look at your database and see if it was actually created?

**Comment by seawolff** [comment]
@bwentzloff all my leagues exist. Is there a particular piece of data you'd like to see? 
<img width="854" alt="Screenshot 2020-02-22 11 02 30" src="https://user-images.githubusercontent.com/147572/75096200-e4ae3700-5562-11ea-9562-cdf1c7e708a9.png">
<img width="1233" alt="Screenshot 2020-02-22 11 02 47" src="https://user-images.githubusercontent.com/147572/75096201-e546cd80-5562-11ea-9c6a-49879f1c0b15.png">

```

id | name | maxSize | created_at | updated_at | commish_id | invite_code | draft_datetime | draft_status | qbs | rbs | wrs | tes | flex | ks | def | playoff_length | league_type | bench | waiver_day | draft_nextpick | draftpick_time | draft_current_drafter | teamQbs | teamKs | superflex | rule1 | rule2 | rule3 | rule4 | rule5 | rule6 | rule7 | rule8 | rule9 | rule10 | rule11 | rule12 | rule13 | rule14 | rule15 | rule16 | rule17 | rule18 | rule19 | rule20 | rule21 | rule22 | rule23 | rule24 | rule25 | rule26 | rule27 | rule28 | rule29 | rule30 | rule31 | rule32 | rule33 | rule34 | waiver_status | week
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | Test League | 8 | 2020-02-22 06:21:38 | 2020-02-22 06:21:38 | 1 | 5e50c87213103 | 2020-02-22 06:21:38 | 0 | 1 | 2 | 2 | 1 | 1 | 1 | 1 | 2 | 1 | 4 | Wednesday |   | 5 |   | 0 | 0 | 0 | 6 | 6 | 6 | 6 | 4 | 1 | 2 | 3 | 1 | 2 | 3 | 1 | 1 | 1 | -2 | -2 | 5 | 4 | 3 | 3 | 2 | 2 | 2 | 2 | 1 | 0.5 | 10 | 8 | 6 | 2 | 1 | 0 | -2 | -4 | 0 | 1
2 | Poop | 2 | 2020-02-22 06:54:18 | 2020-02-22 06:54:18 | 1 | 5e50d01a9bcd2 | 2020-02-22 06:54:00 | 0 | 1 | 2 | 2 | 1 | 1 | 1 | 1 | 2 | 1 | 4 | Wednesday |   | 5 |   | 0 | 0 | 0 | 6 | 6 | 6 | 6 | 4 | 1 | 2 | 3 | 1 | 2 | 3 | 1 | 1 | 1 | -2 | -2 | 5 | 4 | 3 | 3 | 2 | 2 | 2 | 2 | 1 | 0.5 | 10 | 8 | 6 | 2 | 1 | 0 | -2 | -4 | 0 | 1
3 | Poop 2 | 2 | 2020-02-22 06:55:26 | 2020-02-22 06:55:26 | 1 | 5e50d05eb3580 | 2020-02-22 06:57:00 | 0 | 1 | 2 | 2 | 1 | 1 | 1 | 1 | 2 | 1 | 4 | Wednesday |   | 5 |   | 0 | 0 | 0 | 6 | 6 | 6 | 6 | 4 | 1 | 2 | 3 | 1 | 2 | 3 | 1 | 1 | 1 | -2 | -2 | 5 | 4 | 3 | 3 | 2 | 2 | 2 | 2 | 1 | 0.5 | 10 | 8 | 6 | 2 | 1 | 0 | -2 | -4 | 0 | 1
4 | Test League | 2 | 2020-02-22 16:56:33 | 2020-02-22 16:56:33 | 1 | 5e515d41c5f79 | 2020-02-23 16:56:00 | 0 | 1 | 2 | 2 | 1 | 1 | 1 | 1 | 2 | 1 | 4 | Wednesday |   | 5 |   | 0 | 0 | 0 | 6 | 6 | 6 | 6 | 4 | 1 | 2 | 3 | 1 | 2 | 3 | 1 | 1 | 1 | -2 | -2 | 5 | 4 | 3 | 3 | 2 | 2 | 2 | 2 | 1 | 0.5 | 10 | 8 | 6 | 2 | 1 | 0 | -2 | -4 | 0 | 1


```

**Comment by seawolff** [comment]
Pretty sure you can recreate my setting up a new empty sql.lite db and creating a league. I recreate this error with each new created league.

**Comment by bwentzloff** [comment]
Oh! I see the problem. I’ll update the docs shortly. In the meantime you need to add the following record to the “sport” table:

Id: 8
Name: XFL
Current_week: 1

**Comment by seawolff** [comment]
@bwentzloff hey that got rid of that error but still no data on the league page. No logs during creating or viewing the league sorry.

**Comment by bwentzloff** [comment]
There probably won’t be much of anything there until you invite other users, add players, have your draft, etc. Check out example_database.sql in the repo. It can help you preload all of that stuff.

**Comment by kenjdavidson** [comment]
For some reasons migrations

Migrating: 2020_02_10_192024_add_fields_for_standings
Migrated:  2020_02_10_192024_add_fields_for_standings (0 seconds)
Migrating: 2020_02_10_192034_add_fields_for_standings
Migrated:  2020_02_10_192034_add_fields_for_standings (0 seconds)

aren't actually being applied, have to manually add wins, losses, ties, pf, and pa.  Really not sure why this is the only migration not happening. 

Still getting a random error about line 94 of the script not having matching columns - but at least there are no more errors in the log.

**Comment by kenjdavidson** [comment]
Got a chance to look into it a little more.  Line 124 on the database_example.sql isn't right.  It looks like the file is missing a large number of either draft_picks or draft_queues rows.
